name: Application Build

on:
  workflow_dispatch:

jobs:
  build:
    name: setup nodejs * application build
    runs-on: self-hosted

    steps:
      - name: setup Nodejs
        run: echo "Hello Hello."
